Created first react component
gosupark27/Shoe-Repair-Management pull request #3
Opened 2021-02-26 05:05 UTC by gosupark27

Creating my first pull request for resolving issue #1

2021-02-26 06:27 UTC, gosupark27 commented
Used grid layout to create a 2x3 grid for the textboxes, created state variables for the rest of the form fields and added a create ticket button.

2021-02-26 23:25 UTC, thatzacdavis commented
Make sure you add `/node_modules` to your `.gitignore`

2021-02-26 23:30 UTC, thatzacdavis commented on api/routes/ticket.js
> +
```suggestion
```
Extra whitespace tends to make files longer with no real benefits.

2021-02-26 23:38 UTC, thatzacdavis commented on api/routes/ticket.js
> +//Save Ticket
```suggestion
// Save Ticket 
```

Generally, there is a space before the beginning of a comment.

2021-02-26 23:39 UTC, thatzacdavis commented on client/src/component/ticketForm.js
> +        axios.put(url, ticketData)
https://www.w3schools.com/tags/ref_httpmethods.asp#:~:text=PUT%20is%20used%20to%20send,that%20PUT%20requests%20are%20idempotent.&text=In%20contrast%2C%20calling%20a%20POST,the%20same%20resource%20multiple%20times.

So this technically depends on how we build the API.

2021-02-26 23:48 UTC, thatzacdavis commented on client/src/component/ticketForm.js
> +    //   };
```suggestion
```

We don't need this anymore so there's no point in leaving it.

2021-02-26 23:49 UTC, thatzacdavis commented on client/src/component/ticketForm.js
> +    //Axios Put request
```suggestion
```

Generally, comments are there to provide context surround what the code is doing. We can see that the code is going to make a PUT w/ Axios, so comments like these aren't really necessary.

2021-02-27 00:13 UTC, thatzacdavis requested changes
Overall, this is a really good start. You've picked up how the component library works very well.

Let's get those comments and the whitespace cleaned up though.

Other than that and any comments I put inline, I'm not usually a fan of having a bunch of console logs, but maybe we can clean them up later.

2021-03-02 17:57 UTC, merged